language: java
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  sonarcloud:
    organization: "guilhermedelemos-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
