language: java
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  sonarcloud:
    organization: "guilhermedelemos-github"
    token:
      secure: "XbSMrPJaRYfzOMRPLCxh9/C8MTN6OGrAHRSP9S8aLCHj3kuKWfzxyOHDS/g1rc+Ypf1PlSEkRSWAplE16ihElxo7eK5uAuQ1BdSWKO209UF6+F0VRU8MW1elYG5WoQmOZ6ZvIE/hUjXm951eiVOLGn1x86EprmZGOYuh6Kgo3g3Ya2gZyPEbXDRDEbl+r7YF6yLbubiwQiJihITfu0q2I/WVlwo/I1CZc95dMotBx+XizNu/ZQZHN/gM6gFvKattzjWdBWds7tInJFUtJA1na6Hgah1hBoeJ37VuQegEPHHAQ7BSVKwB4/kyUg0lDNBJQX14CCRhNSJ+Q6BcWm9MfyIbt+ArycarSRk5jfD/mfsUW0rtUieGgDZHZNZ/XH9kgI9ZWOjvyT6pNmbEg1GrQdlpjwUBYKJBCgUMSggeq1GvQdTLDaRllVKQPPmUgLee/yh8mnnohWImn7M5z5HXiSlJvBWeu564SyEbBUhvLIvGomWwQEoKyQU2KaP9FxI4kE1419TOyzLVPfpJC0kjxVCbsuIvxEP744E7KzThy4myB2BnRdWL8CvUmuCtKMV/WS79EJd/F6TLCXfK4NXjSgbxEwpnsLU6BHJen7lyIyGAZPCrmMie7RIr9vUiBsdiCG5hO5XaUpf1c8dj3Affu2Ao0LJbxU7lb1GD8rWsZsQ="
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
